Books model and crud
iambrozjak/library pull request #1
Opened 2023-10-15 11:38 UTC by iambrozjak

2023-10-16 20:55 UTC, loqimean commented on app/controllers/books_controller.rb
> +  before_action :set_book, only: %i[ show edit update destroy ]
видаляй, юзай явно змінні

2023-10-16 20:55 UTC, loqimean commented on app/controllers/books_controller.rb
> +        format.json { render json: @book.errors, status: :unprocessable_entity }
навіщо тобі це?)

2023-10-29 21:12 UTC, loqimean requested changes

2023-10-29 21:12 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +  }
винеси в окремі файли

2023-10-29 21:12 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +@tailwind utilities;
чому це знизу?

2023-10-29 21:12 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +
```suggestion
```

2023-10-29 21:12 UTC, loqimean commented on app/controllers/books_controller.rb
> +
```suggestion
```

2023-10-29 21:12 UTC, loqimean commented on app/controllers/books_controller.rb
> +      redirect_to book_path(@book)
обєʼднай

2023-10-29 21:12 UTC, loqimean commented on app/controllers/books_controller.rb
> +      flash[:alert] = "Book was not created."
```suggestion
      flash[:alert] = "Book was not created."

```

2023-10-29 21:12 UTC, loqimean commented on app/controllers/books_controller.rb
> +      redirect_to book_path(@book), status: :see_other
теж обʼєднай

2023-10-29 21:12 UTC, loqimean commented on app/controllers/books_controller.rb
> +      redirect_to book_path(@book), status: :see_other
і так скрізь

2023-10-29 21:12 UTC, loqimean commented on app/helpers/application_helper.rb
> +end
де нова строка?

2023-10-29 21:12 UTC, loqimean commented on app/helpers/books_helper.rb
навіщо тобі цей пустий файл?

2023-10-29 21:12 UTC, loqimean commented on app/models/book.rb
> +    validates :title, :author, presence: true
чому тут чотири пробіли, а не 2, як має бути?

2023-10-29 21:12 UTC, loqimean commented on app/views/books/_book.html.erb
> +
```suggestion
```

2023-10-29 21:12 UTC, loqimean commented on app/views/books/_book.json.jbuilder
тобі точно потрібен цей файл?

2023-10-29 21:12 UTC, loqimean commented on app/views/books/_form.html.erb
> +<%= simple_form_for @book, defaults: { input_html: { class: "form_input" } }, html: { class: "contents" } do |form| %>
куди звертається ця форма? я не бачу передавання шляху

2023-10-29 21:12 UTC, loqimean commented on app/views/books/_form.html.erb
> +
```suggestion
```

2023-10-29 21:12 UTC, loqimean commented on app/views/books/_form.html.erb
> +
```suggestion
```

2023-10-29 21:12 UTC, loqimean commented on app/views/books/_form.html.erb
> +    <%= form.input :description, as: :text %>
навіщо передавати тип? сімпл-форм сам його визначає

2023-10-29 21:12 UTC, loqimean commented on app/views/books/edit.html.erb
> +    <%= render  partial: "books/form", book: @books %>
```suggestion
  <%= render  partial: "books/form", book: @books %>
```

2023-10-29 21:12 UTC, loqimean commented on app/views/books/edit.html.erb
> +    <%= render  partial: "books/form", book: @books %>
чому локал змінна одної книги, а ти передаєш інстанс змінну в множині?

2023-10-29 21:12 UTC, loqimean commented on app/views/books/index.html.erb
> +
зайва строка..

2023-10-29 21:12 UTC, loqimean commented on app/views/books/index.html.erb
> +
зайва строка..

2023-10-29 21:12 UTC, loqimean commented on app/views/books/index.html.erb
> +    <%= render  partial: "books/book", collection: @books %>
```suggestion
    <%= render partial: "books/book", collection: @books %>
```

2023-10-29 21:12 UTC, loqimean commented on app/views/books/index.json.jbuilder
тобі точно треба цей файл?

2023-10-29 21:12 UTC, loqimean commented on app/views/layouts/_flash.html.erb
> +<% if flash.any? %>
навіщо ця перевірка?

2023-10-29 21:12 UTC, loqimean commented on app/views/layouts/_flash.html.erb
> +<% end %>
де нова строка?

2023-10-29 21:12 UTC, loqimean commented on app/views/layouts/application.html.erb
> +
```suggestion
```

2023-10-29 21:12 UTC, loqimean commented on config/application.rb
> + end
```suggestion
end
```

2023-10-29 21:12 UTC, loqimean commented on config/routes.rb
> +
просто куча зайвих нових строк....

2023-10-29 21:12 UTC, loqimean commented on config/routes.rb
> +  root "books#index"
рут зазвичай зверху пишуть

2023-10-29 21:12 UTC, loqimean commented on config/routes.rb
> +  # get "up" => "rails/health#show", as: :rails_health_check
чому ти закоментувала цей шлях?

2023-10-29 21:12 UTC, loqimean commented on db/migrate/20231012204425_create_books.rb
> +      t.string :isbn
а книга може без цього коду бути?

2023-10-29 21:12 UTC, loqimean commented on db/seeds.rb
> +FactoryBot.create_list(:book, 50)
де нова строка?

2023-10-29 21:12 UTC, loqimean commented on spec/helpers/books_helper_spec.rb
навіщо тобі цей пустий файл?

2023-10-29 21:12 UTC, loqimean commented on spec/helpers/books_helper_spec.rb
видаляй

2023-10-29 21:12 UTC, loqimean commented on spec/models/book_spec.rb
> +
видаляй цю строоку

2023-10-29 21:12 UTC, loqimean commented on spec/models/book_spec.rb
> +
ці дві теж

2023-10-29 21:12 UTC, loqimean commented on spec/requests/books_spec.rb
> +  let(:invalid_attributes) { { title: "" } }
можеш заюзати трейт та атрібютс фор

2023-10-29 21:12 UTC, loqimean commented on spec/requests/books_spec.rb
> +  it "is successful" do
чому дескрайби на рівні з іт-ами?

2023-10-29 21:12 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
не бачу тестування на присутність бодай одного відрендереного рекорда

2023-10-29 21:12 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
чому різний рівень?

2023-10-29 21:12 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
і так скрізь, де це потрібно

2023-10-29 21:12 UTC, loqimean commented on spec/requests/books_spec.rb
> +        expect(response).to redirect_to(book_url(book))
а де тестування присутності флеш-месиджа?

2023-10-29 21:12 UTC, loqimean commented on spec/requests/books_spec.rb
> +  book =  Book.create!(title:'Look to Windward', author:'Benjamin Wolf', isbn:'9372731109575', description:'Fantasy')
ми локал змінні в тестах НЕ юзаємо

2023-10-29 21:12 UTC, loqimean commented on spec/requests/books_spec.rb
> +  book.save
а це що таке??

2023-10-29 21:12 UTC, loqimean commented on spec/requests/books_spec.rb
> +  expect(Book.find_by(title: 'Look to Windward')).to be_nil
що це за тест в ріквесті папці??

2023-10-29 21:12 UTC, loqimean commented on spec/requests/books_spec.rb
> +  expect(Book.find_by(title: 'Look to Windward')).to be_nil
ти тестуєш рельсові методи? чи маєш РІКВЕСТ на деліт тестувати?

2023-11-01 18:16 UTC, loqimean commented on .gitignore
> +app/assets/builds/tailwind.css
```suggestion
app/assets/builds/tailwind.css

```

2023-11-02 07:50 UTC, loqimean requested changes

2023-11-02 07:50 UTC, loqimean commented on app/assets/builds/tailwind.css
цього тут не мало би бути

2023-11-02 07:50 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +@tailwind utilities;
імпорт має бути нижче підключення головних стилів

2023-11-02 07:50 UTC, loqimean commented on app/controllers/books_controller.rb
> +      params.require(:book).permit(:title, :author, :isbn, :description)
```suggestion
    params.require(:book).permit(:title, :author, :isbn, :description)
```

2023-11-02 07:50 UTC, loqimean commented on app/helpers/books_helper.rb
видаляй пустий файл

2023-11-02 07:50 UTC, loqimean commented on app/views/books/_book.html.erb
> +    <%= link_to "Edit this book",  edit_book_path(book), class: "btn" %>
```suggestion
  <%= link_to "Show this book",  book, class: "btn" %>
  <%= link_to "Edit this book",  edit_book_path(book), class: "btn" %>
```

2023-11-02 07:50 UTC, loqimean commented on app/views/books/edit.html.erb
> +    <%= render "books/form", book: @book %>
```suggestion
  <%= render "books/form", book: @book %>
```

2023-11-02 07:50 UTC, loqimean commented on app/views/books/new.html.erb
> +   <%= render  "books/form", book: @book %>
```suggestion
  <%= render  "books/form", book: @book %>
```

2023-11-02 07:50 UTC, loqimean commented on app/views/books/show.html.erb
> +      <%= render "books/book", book: @book %>
що ж у тебе з відступами)

2023-11-02 07:50 UTC, loqimean commented on config/routes.rb
> +  # get "up" => "rails/health#show", as: :rails_health_check
те ж питання

2023-11-02 07:50 UTC, loqimean commented on spec/helpers/books_helper_spec.rb
видаляй пустий файл

2023-11-02 07:50 UTC, loqimean commented on spec/requests/books_spec.rb
> +  let(:invalid_attributes) { { title: "" } }
те ж саме)

2023-11-02 07:50 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response.body).to include("Books")
в цьому сенсу нема

2023-11-02 07:50 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response.body).to include("Books")
і де перевірка статусу запита?)

2023-11-02 07:50 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response.body).to include(book.title)
те ж

2023-11-02 07:50 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response.body).to include("New book")
міняй

2023-11-02 07:50 UTC, loqimean commented on spec/requests/books_spec.rb
> +
```suggestion
```

2023-11-02 07:50 UTC, loqimean commented on spec/requests/books_spec.rb
> +
```suggestion
```

2023-11-05 12:16 UTC, loqimean requested changes

2023-11-05 12:16 UTC, loqimean commented on app/assets/builds/tailwind.css
> +.flash-notice{background-color:rgb(240 253 244/var(--tw-bg-opacity));color:rgb(21 128 61/var(--tw-text-opacity))}.flash-alert,.flash-notice{--tw-bg-opacity:1;--tw-text-opacity:1;border-radius:.5rem;d
Досі актуально

2023-11-05 18:26 UTC, loqimean commented on app/views/books/_book.html.erb
> +    <%= link_to "Edit this book",  edit_book_path(book), class: "btn" %>
Актуально

2023-11-05 18:26 UTC, loqimean commented on app/views/books/edit.html.erb
> +    <%= render "books/form", book: @book %>
Теж

2023-11-05 18:26 UTC, loqimean commented on app/views/books/index.html.erb
> +    <%= render  partial: "books/book", collection: @books %>
Теж

2023-11-05 18:27 UTC, loqimean commented on app/views/books/new.html.erb
> +   <%= render  "books/form", book: @book %>
Теж, а також зайвий пробіл всередині

2023-11-05 18:27 UTC, loqimean commented on app/views/books/show.html.erb
> +      <%= render "books/book", book: @book %>
І зайва нова строка зверху

2023-11-05 18:27 UTC, loqimean commented on config/application.rb
> + end
Теж

2023-11-05 18:28 UTC, loqimean commented on config/routes.rb
> +  # get "up" => "rails/health#show", as: :rails_health_check
Теж

2023-11-05 18:28 UTC, loqimean commented on spec/helpers/books_helper_spec.rb
Теж

2023-11-05 18:29 UTC, loqimean requested changes

2023-11-05 18:29 UTC, loqimean commented on spec/factories/books.rb
> +
```suggestion
```

2023-11-05 18:29 UTC, loqimean commented on spec/models/book_spec.rb
> +    expect(book.valid?).to eq true
be_persisted

2023-11-05 20:37 UTC, loqimean commented on app/views/books/edit.html.erb
> +    <%= render "books/form", book: @book %>
Актуааально

2023-11-05 20:37 UTC, loqimean commented on app/views/books/index.html.erb
> +    <%= render  partial: "books/book", collection: @books %>
Теж

2023-11-06 15:50 UTC, loqimean commented on spec/helpers/books_helper_spec.rb
видаляй

2023-11-06 19:46 UTC, mdotvasylenchuk commented on app/assets/stylesheets/components/flash.css
> +}
чому в layer не загорнула?

2023-11-06 21:11 UTC, loqimean approved these changes

2023-11-06 21:11 UTC, loqimean commented on app/assets/stylesheets/components/flash.css
> +@layer components {
видаляй леєр

2023-11-06 21:11 UTC, loqimean commented on app/assets/stylesheets/components/flash.css
> +@layer components {
це не працюватиме

2023-11-06 21:39 UTC, loqimean approved these changes

2023-11-07 11:13 UTC, merged